config/routes.rb
Rails.application.routes.draw do
  get 'photos/create'

  devise_for :users, :controllers => { registrations: 'registrations' }
mount Like::Engine => '/'
  root 'welcome#index'

  get 'fixits/thanks'

  get 'semps/basic'
  get 'semps/alcohol'
  get 'semps/sobers'
  get 'semps/sizing'

  resources :orders

  resources :fixits
  
  resources :items do
    resources :orders
  end

  resources :ideas, shallow: true do
    resources :photos
  end

  resources :items, shallow: true do
    resources :photos
  end 
  resources :ideas do
    resources :items
  end

  resources :items do
    resources :charges
  end

  resources :charges

  resources :idea do
    resources :comments
  end

  resources :users do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
  belongs_to :user
  belongs_to :item
end

app/models/fixit.rb
class Fixit < ActiveRecord::Base
  belongs_to :user
  has_attached_file :pic
  validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :comments
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :name, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :idea
	belongs_to :user
	has_many :photos, :dependent => :destroy 
	has_many :orders
	validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
	validates :name, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :item
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :idea
	belongs_to :item

  	has_attached_file :image,
    	:path => ":rails_root/public/images/:id/:filename",
    	:url  => "/images/:id/:filename"

  	do_not_validate_attachment_file_type :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum role: [:user, :admin] #defaults to user
  has_many :comments
  has_many :ideas
  has_many :items
  has_many :fixits
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/fixits_controller.rb
class FixitsController < ApplicationController
	def new
		@fixit = Fixit.new
		@user = current_user
	end

	def create
		@fixit = Fixit.new
		@fixit.user_id = current_user.id
		@user = current_user
		if @fixit.save
			UserMailer.fixit_email(@user).deliver_now
			redirect_to fixits_thanks_path(@fixit)
		else
			render 'new'
		end
	end

	def thanks
	end

	private
	def fixit_params
  		params.require(:fixit).permit(:pic,:name,:description,:location)
	end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
	def index
		@user = current_user
		@ideas = Idea.order(:updated_at).reverse_order   #eventually will be able to filter by year
	end


	def show
		@idea = Idea.find(params[:id])
		@photos = Photo.where(idea_id: @idea.id)
		@comments = Comment.where(idea_id: @idea.id)
	end

	def new
		@idea = Idea.new
		@user = current_user
	end



	def create
  		@idea = Idea.new(idea_params)
  		@idea.user_id = current_user.id
  		respond_to do |format|
    		if @idea.save
     
      			if params[:images]
        #===== The magic is here ;)
        			params[:images].each { |image|
          			@idea.photos.create(image: image)
        		}
      			end

      			format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
      			format.json { render json: @idea, status: :created, location: @idea }
    		else
      		format.html { render action: "new" }
      		format.json { render json: @idea.errors, status: :unprocessable_entity }
    		end
  		end
	end


	def edit
		@idea = Idea.find params[:id]
	end

	def update
		@idea = Idea.find params[:id]
		authorize @idea
		if @idea.update(idea_params)
			redirect_to idea_path(@idea)
		else
			render 'edit'
		end
	end

	def destroy
		@idea = Idea.find(params[:id])
		@idea.destroy
		redirect_to ideas_path
	end

	private
		def idea_params
			params.require(:idea).permit(:name, :description, :price)
		end






end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = Item.order(:updated_at).reverse_order
	end

	def show
		@item = Item.find(params[:id])
		@photos = Photo.where(item_id: @item.id)
	end

	def new
		@item = Item.new
		@user = current_user
	end

	def create
		if params[:idea_id]
			@idea = Idea.find(params[:idea_id])	
			@item = Item.new
			@item.name = @idea.name
			@item.description = @idea.description
			@item.price = @idea.price
			@item.photos = @idea.photos
			
			@photos = Photo.where(idea_id: @idea.id)
			@photos.each do |photo|
				photo.item_id = @item_id
				photo.save!
			end

			@item.user_id = @idea.user_id
			@item.save!
			@idea.destroy
		else
			@item = Item.new(item_params)
  			@item.user_id = current_user.id
  			@item.save!
		end
		
		redirect_to items_path
	end


	def edit
		@item = Item.find params[:id]
	end

	def update
		@item = Item.find params[:id]
		if @item.update(item_params)
			redirect_to item_path(@item)
		else
			render 'edit'
		end
	end


	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to items_path
	end


	private
		def item_params
			params.require(:item).permit(:name, :description, :price)
		end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def index
		@item = Item.find(params[:item_id])
		@orders = @item.orders.all
		@orders_grid = initialize_grid(@orders,
			name: "ordersheet",
			enable_export_to_csv: true,
			csv_file_name: "OrderSheetExportCSV"
			)

		export_grid_if_requested('ordersheet' => 'orders_grid') do
      # usual render or redirect code executed if the request is not a CSV export request
    end
	end

	def show

	end  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def new 
    if params[:item_id]
      @parent = Item.find params[:item_id]
    else
      @parent = Idea.find params[:idea_id]
    end

    @photo = @parent.photos.build
                     
  end

  def create
    if params[:item_id]
      @item = Item.find params[:item_id]
      @photo = @item.photos.build(photo_params)
      if @photo.save
        redirect_to item_path(@item)
      else
        render 'new'
      end
    elsif params[:idea_id]
      @idea = Idea.find params[:idea_id]
      @photo = @idea.photos.build(photo_params)
      if @photo.save
        redirect_to idea_path(@idea)
      else
        render 'new'
      end
    else
      raise 'error'
    end
  end
    

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.item_id
      @photo.destroy
      redirect_to item_path(@photo.item)
    else
      @photo.destroy
      redirect_to idea_path(@photo.idea)
    end
  end

  private
  	def photo_params
      params.require(:photo).permit(:image)
  	end
end

app/controllers/semps_controller.rb
class SempsController < ApplicationController
	def basic
	end
	def alcohol
	end
	def sizing
	end
	def sobers
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fixits_helper.rb
module FixitsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
	def special_thing(parent)
		case parent
		when Idea
			idea_photos_path(parent)
		when Item
			item_photos_path(parent)
		end
	end

	def back_button(parent)
		case parent
		when Idea
			idea_path(parent)
		when Item
			item_path(parent)
		end
	end
end

app/helpers/semps_helper.rb
module SempsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fixits/new.html.erb
<style type="text/css">
	.myclass{
		text-align: center;
		font-size: 16px;
		margin-bottom: 10px;
	}
	.picadd{
		margin-bottom: 10px;
		display: block;
		margin-right: auto;
		margin-left: auto;
	}


</style>

<br>
<br>
<br>
<br>
<h1>Submit a new Fixit Request</h1>
<br>
<div class="border-form-div">

<%= form_for @fixit, html: {multipart: true} do |f| %>

	<%= f.text_field :name, :placeholder => "Name" %>
	<%= f.text_area :description, :placeholder => "Description", rows: 3, cols: 27, :class => 'myclass' %>
	<%= f.text_field :location, :placeholder => "Location" %>
	<%= f.file_field :pic, :class => 'picadd' %>
	<%= f.submit "create", :class=>"btn btn-primary"%>

<% end %>

</div>

app/views/fixits/thanks.html.erb
<style type="text/css">
	p{
		text-align: center;
		font-size: 25px;
		font-style: italic;
	}
	h1{
	
	}

</style>


<br>
<br>
<br>
<br>



<h1>Thanks for the submission!</h1>
<p>An email has been sent to the house manager.</p>

<p> <%= link_to 'Submit Another Request', new_fixit_path, class: "btn btn-primary btn-lg outline" %> </p>

app/views/ideas/_form.html.erb
<div class="border-form-div">

<%= form_for @idea, html: {multipart: true} do |f| %>

	<%= f.text_field :name, :placeholder => "Idea Name" %>
	<%= f.text_field :description, :placeholder => "Description" %>
	<%= f.text_field :price, :placeholder => "Price" %>
	<%= f.submit "create", :class=>"btn btn-primary"%>

<% end %>

</div>

	

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>
<%= render 'form' %>

app/views/ideas/index.html.erb
<style type="text/css">
	.title{
		text-align: center;
	}

	.new-idea{
		text-align: center;
	}

	img{
		display: block;
		margin-left: auto;
		margin-right: auto;
	}

	.created{
		text-align: center;
		font-size: 13px;
	}


</style>


	<br/><br/><br/>
	<h1>All Ideas </h1>
	
	<div class="new-idea">
		<%= button_to "Add an Idea", new_idea_path, :class => "btn btn-info btn-lg raised", :method => :get %>
	</div>

	</h1>
	<div class="row">
	<% @ideas.each do | idea |%>
		<div class="col-sm-6 col-md-4 col-lg-3 item-image-box">
			
			<% if idea.photos.first %>
				<td><%= link_to image_tag((idea.photos.first.id.to_s + "/" + idea.photos.first.image_file_name), height: 250, width: 250) , idea_path(idea) %></td>
			<% else %>
				<td><%= link_to image_tag('default-image.png', height: 250, width: 250) , idea_path(idea) %></td>
			<% end %>
			<p class="title"> <%= idea.name %> </p>
			<p class="created"> Created by <%= idea.user.first_name %> <%= idea.user.last_name %></p>

		</div>
	<% end %>
	</div>

app/views/ideas/new.html.erb
<h1>New Idea</h1>
<%= render 'form' %>

app/views/ideas/show.html.erb
<style type="text/css">
	.delete{
		text-align: center;
	}
	.col-sm-5{
		background-color: rgba(255,255,255,.2);
	}
	.comment{
		margin-bottom: 0px;
		margin-top: 25px;
	}
	.ct{
		overflow: scroll;
		font-size: 15px;
	}
	.add_com{
		margin-top: 30px;
	}
	.des{
		text-align: center;
		overflow: scroll;
	}
	.console{
		padding-left: 10px;
	}
</style>


<br/><br/><br/><br/>

<div class="row">
	<div class="col-sm-7">
		<h1> $<%= @idea.price %> <%= @idea.name %> </h1>
		<h1>
		<% if Like::Like.liking?(current_user, @idea) %> <!--This is Better -->
  			<%= link_to "dislike", like_path_for(@idea), :class=>"btn btn-default btn-xs", method: :delete %>
		<% else %>
  			<%= link_to 'like', like_path_for(@idea), :class=>"btn btn-primary btn-xs",method: :post %>
		<% end %>
		<%=Like::Like.with_likeable(@idea).count%>
		</h1>

		
		<div class="row row-centered">
		<% @photos.each do |photo| %>
			<div class="col-sm-6 col-centered item-image-box">
				<%= image_tag(photo.id.to_s + "/" + photo.image_file_name, class: 'img-responsive') %>
				<% if current_user.admin? || current_user == @idea.user %>
					<p class="delete"> <%= link_to 'Delete Photo', photo_path(photo), method: :delete, data:{ confirm: "Are you sure?" } %> </p>
				<% end %>
			</div>
		<% end %>
		</div>
		<p class="des"><%= @idea.description %> </p>
	</div>


	<div class="col-sm-5">

		<h2>Comments</h2>

		<% @comments.each do |comment| %>
			<p class="comment"><%= User.find(comment.user_id).first_name.first %>. <%= User.find(comment.user_id).last_name %>:</p>
			<p class="ct"><%= comment.text %> </p>
	  		<%= link_to 'Destroy Comment', [comment.idea, comment],
	        	method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	 
		<p class="add_com">Add a comment:</p>
		<p class="center"><%= render 'comments/form' %></p>

	</div>
</div>



<% if policy(@idea).update? %>
	<% if current_user.admin? %>
	<p class="console"> Admin Console: </p>
	<p> <%= link_to 'Push To Store' , idea_items_path(@idea), class: "btn btn-primary btn-lg outline",method: :post %></p>
	
	<% else %>
	<p class="console"> Creator Console: </p>
	<% end %>
<p> <%= link_to 'Add new photo', new_idea_photo_path(@idea), class: "btn btn-primary btn-lg outline" %> </p>
<p> <%= link_to 'Edit', edit_idea_path(@idea), class: "btn btn-primary btn-lg outline" %> </p>
<p> <%= link_to 'Destroy', idea_path(@idea), class: "btn btn-primary btn-lg outline", method: :delete, data:{ confirm: "Are you sure?" } %> </p>
<% end %>

app/views/items/_form.html.erb
<div class="border-form-div">

<%= form_for @item, html: {multipart: true} do |f| %>

	<%= f.text_field :name, :placeholder => "Idea Name" %>
	<%= f.text_field :description, :placeholder => "Description" %>
	<%= f.text_field :price, :placeholder => "Price" %>
	<%= f.submit "create", :class=>"btn btn-primary"%>

<% end %>

</div>

app/views/items/edit.html.erb
<h1>Edit item</h1>
<%= render 'form' %>

app/views/items/index.html.erb
<style type="text/css">
	.title{
		text-align: center;
	}

	.td{
		text-align: center;
	}

	div{
		text-align: center;
	}

	img{
		display: block;
		margin-left: auto;
		margin-right: auto;
	}

	.created{
		text-align: center;
		font-size: 13px;
	}


</style>



	<br/><br/><br/>
	<h1>Shop Items</h1>

	<% if current_user.admin? %>
	<div>
	<%= button_to "Add an item", new_item_path, :class => "btn btn-info btn-lg raised", :method => :get %>
	</div>
	
<% end %>
	<div class="row">
	<% @items.each do | item |%>
		<div class="col-sm-6 col-md-4 col-lg-3 item-image-box">
			
			<% if item.photos.first %>
				<td><%= link_to image_tag((item.photos.first.id.to_s + "/" + item.photos.first.image_file_name), height: 250, width: 250) , item_path(item) %></td>
			<% else %>
				<td><%= link_to image_tag('default-image.png', height: 250, width: 250) , item_path(item) %></td>
			<% end %>
			<p class="title"> <%= item.name %> </p>
			<p class="created"> Created by <%= User.find(item.user_id).first_name %> <%= User.find(item.user_id).last_name %></p>

		</div>
	<% end %>
	</div>

app/views/items/new.html.erb
<h1>New item</h1>
<%= render 'form' %>

app/views/items/show.html.erb
<style>
	.des{
		text-align: center;
	}
</style>

<br/><br/><br/>

<h1> $<%= @item.price %> <%= @item.name %> </h1>


<div class="row row-centered">
<% @photos.each do |photo| %>
	<div class="col-sm-3 col-centered item-image-box">
		<%= image_tag(photo.id.to_s + "/" + photo.image_file_name, class: 'img-responsive') %>
		<% if current_user.admin? || current_user == @item.user %>
		<p class="des"> <%= link_to 'Delete Photo', photo_path(photo), method: :delete, data:{ confirm: "Are you sure?" } %> </p>
		<% end %>
	</div>
<% end %>

<br/>
<p class="des"><%= @item.description %></p>
<p class="des"><%='Total Orders = ' "#{@item.orders.count}"%></p>
</div>


<p> <%= render 'charges/form' %></p>


<% if current_user.admin? %>
	<p class="console"> Admin Console: </p>
	<p> <%= link_to 'Add new photo', new_item_photo_path(@item), class: "btn btn-primary btn-lg outline" %> </p>
	<p> <%= link_to 'Orders', item_orders_path(@item), class: "btn btn-primary btn-lg outline" %> </p>
	<p> <%= link_to 'Edit', edit_item_path(@item), class: "btn btn-primary btn-lg outline" %> </p>
	<p> <%= link_to 'Destroy', item_path(@item), method: :delete, data:{ confirm: "Are you sure?" }, class: "btn btn-primary btn-lg outline" %> </p>
<% end %>

<br/><br/><br/>

app/views/orders/_orders_grid.html.erb
<%= grid(@orders_grid, html: {class: 'my-grid'}, hide_csv_button: true) do |g|

  g.column name:  'Name' do |order|
    order.name
  end

  g.column name:  'Size'  do |order|
    order.size
  end

  g.column  name:  'Comment' do |order|
    order.comment
  end

  g.column  name:  'price' do |order|
    order.price
  end

end %>

app/views/orders/index.html.erb
<style type="text/css">
  
  table.my-grid {
    border: 1px solid red;
    color: black;
    background-color: white;
  }
  .table{
  	padding: 10px;
  }
</style>




<h1>Orders for <%=@item.name %></h1>
<h2>Total units ordered: <%=@orders.size%> </h2>
<h2>XS: <%=@orders.where(size: "XS").size%>  S: <%=@orders.where(size: "S").size%>  M: <%=@orders.where(size: "M").size%> L: <%=@orders.where(size: "L").size%> XL: <%=@orders.where(size: "XL").size%> 
</h2>


<div class="table">
<%= render 'orders/orders_grid' %>
</div>
<button class="btn btn-primary wg-external-csv-export-button" data-grid-name="ordersheet">Export To CSV</button>

app/views/photos/_form.html.erb
<style type="text/css">
	p{
		display: block;
		margin-left: auto;
		margin-right: auto;
	}

</style>

<h1>Add a Photo</h1>

<div class="border-form-div">

<%= form_for [@parent, @photo], :url => special_thing(@parent), :html => { :multipart => true } do |form| %>

  <%= form.file_field :image %> <br>
  <%= form.submit :submit, :class=>"btn btn-info btn-lg" %>

<% end %>

</div>


<p>
<%= link_to 'Back' , back_button(@parent), :class=>"btn btn-primary btn-lg back-but" %>
</p>

app/views/photos/new.html.erb
<br/><br/><br/><br/><br/>

<%= render 'form' %>