config/routes.rb
Rails.application.routes.draw do
  get 'photos/create'

  devise_for :users, :controllers => { registrations: 'registrations' }
mount Like::Engine => '/'
  root 'welcome#index'

  get 'fixits/thanks'

  get 'semps/basic'
  get 'semps/alcohol'
  get 'semps/sobers'
  get 'semps/sizing'

  resources :orders

  resources :fixits
  
  resources :items do
    resources :orders
  end

  resources :ideas, shallow: true do
    resources :photos
  end

  resources :items, shallow: true do
    resources :photos
  end 
  resources :ideas do
    resources :items
  end

  resources :items do
    resources :charges
  end

  resources :charges

  resources :idea do
    resources :comments
  end

  resources :users do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
  belongs_to :user
  belongs_to :item
end

app/models/fixit.rb
class Fixit < ActiveRecord::Base
  belongs_to :user
  has_attached_file :pic
  validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :comments
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :name, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :idea
	belongs_to :user
	has_many :photos, :dependent => :destroy 
	has_many :orders
	validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
	validates :name, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :item
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :idea
	belongs_to :item

  	has_attached_file :image,
    	:path => ":rails_root/public/images/:id/:filename",
    	:url  => "/images/:id/:filename"

  	do_not_validate_attachment_file_type :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum role: [:user, :admin] #defaults to user
  has_many :comments
  has_many :ideas
  has_many :items
  has_many :fixits
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
	def index
		@user = current_user
		@ideas = Idea.order(:updated_at).reverse_order   #eventually will be able to filter by year
	end


	def show
		@idea = Idea.find(params[:id])
		@photos = Photo.where(idea_id: @idea.id)
		@comments = Comment.where(idea_id: @idea.id)
	end

	def new
		@idea = Idea.new
		@user = current_user
	end



	def create
  		@idea = Idea.new(idea_params)
  		@idea.user_id = current_user.id
  		respond_to do |format|
    		if @idea.save
     
      			if params[:images]
        #===== The magic is here ;)
        			params[:images].each { |image|
          			@idea.photos.create(image: image)
        		}
      			end

      			format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
      			format.json { render json: @idea, status: :created, location: @idea }
    		else
      		format.html { render action: "new" }
      		format.json { render json: @idea.errors, status: :unprocessable_entity }
    		end
  		end
	end


	def edit
		@idea = Idea.find params[:id]
	end

	def update
		@idea = Idea.find params[:id]
		authorize @idea
		if @idea.update(idea_params)
			redirect_to idea_path(@idea)
		else
			render 'edit'
		end
	end

	def destroy
		@idea = Idea.find(params[:id])
		@idea.destroy
		redirect_to ideas_path
	end

	private
		def idea_params
			params.require(:idea).permit(:name, :description, :price)
		end






end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = Item.order(:updated_at).reverse_order
	end

	def show
		@item = Item.find(params[:id])
		@photos = Photo.where(item_id: @item.id)
	end

	def new
		@item = Item.new
		@user = current_user
	end

	def create
		if params[:idea_id]
			@idea = Idea.find(params[:idea_id])	
			@item = Item.new
			@item.name = @idea.name
			@item.description = @idea.description
			@item.price = @idea.price
			@item.photos = @idea.photos
			
			@photos = Photo.where(idea_id: @idea.id)
			@photos.each do |photo|
				photo.item_id = @item_id
				photo.save!
			end

			@item.user_id = @idea.user_id
			@item.save!
			@idea.destroy
		else
			@item = Item.new(item_params)
  			@item.user_id = current_user.id
  			@item.save!
		end
		
		redirect_to items_path
	end


	def edit
		@item = Item.find params[:id]
	end

	def update
		@item = Item.find params[:id]
		if @item.update(item_params)
			redirect_to item_path(@item)
		else
			render 'edit'
		end
	end


	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to items_path
	end


	private
		def item_params
			params.require(:item).permit(:name, :description, :price)
		end

end

app/controllers/semps_controller.rb
class SempsController < ApplicationController
	def basic
	end
	def alcohol
	end
	def sizing
	end
	def sobers
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fixits_helper.rb
module FixitsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
	def special_thing(parent)
		case parent
		when Idea
			idea_photos_path(parent)
		when Item
			item_photos_path(parent)
		end
	end

	def back_button(parent)
		case parent
		when Idea
			idea_path(parent)
		when Item
			item_path(parent)
		end
	end
end

app/helpers/semps_helper.rb
module SempsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<style type="text/css">
  strong{
    color: ghostwhite;
  }
</style>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li class="dog"><%= link_to image_tag(asset_path('housemom.png'), size:"115x25"), root_path %> </li>
        <li><%= link_to 'Ideas', ideas_path %> </li>
        <li><%= link_to 'Store', items_path %> </li>
        <li><%= link_to 'New Fixit', new_fixit_path %> </li>
      
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">SEMP <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>   <%= link_to 'Basic Info', semps_basic_path %></li>
            <li class="divider">        </li>
            <li>  <%= link_to 'Sizing Regulations', semps_sizing_path %></li>
            <li>  <%= link_to 'Sober Monitors', semps_sobers_path %>  </li>
            <li>  <%= link_to 'Alcohol Rules', semps_alcohol_path %>  </li>
          </ul>
        </li>
      <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if user_signed_in? %> 
          <br>Logged in as 
          <strong><%= current_user.first_name +  " "  + current_user.last_name[0] %></strong>.
          <% if current_user.role == 1 %>
            (Admin)
          <% end %>
          <% end %>
        </li>
        <% if user_signed_in? %> 
        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> </li>
        <% else %>
        <li> <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
        <li> <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<!-- need help on this!!! -->
<script type="text/javascript">
$(".nav li a").on("click", function(){
   $(".nav li").find(".active").removeClass("active");
   $(this).parent().addClass("active") 
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>House Mom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<%= javascript_include_tag "https://js.stripe.com/v1/", type: 'text/javascript' %>
<%= javascript_tag "Stripe.publishableKey = '#{Rails.configuration.stripe[:publishable_key]}';", type: 'text/javascript' %>

<link href='http://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>

<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>


<link href='http://fonts.googleapis.com/css?family=Lobster+Two:700' rel='stylesheet' type='text/css'>
</head>

<body>
<% if user_signed_in? %>
	<%= render 'layouts/nav' %>
<% end %>


<%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>